version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "all"
    versioning-strategy: "auto"
    open-pull-requests-limit: 1
    groups:
      dependencies:
        patterns:
          - "*"
