version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/data_service"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "all"
    versioning-strategy: "auto"
    open-pull-requests-limit: 1
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/user_service"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "all"
    versioning-strategy: "auto"
    open-pull-requests-limit: 1
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/data_service"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/user_service"
    schedule:
      interval: "monthly"
