run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - testdata
  skip-files:
    - ".*_test\\.go$"
  modules-download-mode: readonly

# Output configuration
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

# Linters to enable
linters:
  enable:
    - gofmt # Standard formatting rules.
    - goimports # Formats imports and adds missing imports
    - govet # Checks for subtle bugs and suspicious constructs that might not be caught by the compiler
    - staticcheck # Static analyzer that finds bugs, performance issues, and stylistic problems
    - revive # Replaces golint but with additional customization options
    - errcheck # Ensures that error returns from functions are checked
    - ineffassign # Detects when assignments to variables are never used
    - gosimple # Suggests code simplifications for better readability
    - goconst # Finds repeated strings that could be replaced with constants
    - misspell # Finds commonly misspelled English words in comments
    - gosec # Scans code for security vulnerabilities
    - unused # Checks for unused variables, functions, constants, and types
  disable:
    - maligned   # Deprecated but enabled by default
    - interfacer # Deprecated but enabled by default

# Linter settings
linters-settings:
  goimports:
    local-prefixes: github.com/referendumApp/referendumServices
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
  govet:
    check-shadowing: true
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 3
    min-occurrences: 3

# Issues configuration
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: false  # Set to true to automatically fix issues when possible

# Issues configuration
severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters: [revive]
      severity: warning
