repos:
  - repo: local
    hooks:
      - id: go-mod-tidy
        name: go mod tidy
        language: system
        entry: sh -c "cd atp_service && go mod tidy"
        files: ^atp_service/.*\.go$
        pass_filenames: false

  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: bash -c 'cd atp_service && golangci-lint run ./...'
        language: system
        files: ^atp_service/.*\.go$
        pass_filenames: false

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
        files: ^atp_service/
      - id: go-vet
        files: ^atp_service/
      - id: golangci-lint
        files: ^atp_service/

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        args:
          - --line-length=100
          - --include='\.pyi?$'
          - --exclude="""\.get |
            \.__pycache__|
            \.mypy_cache|
            \.venv|
            build|
            dist"""
        language_version: python3.11
        files: ^data_service/
