repos:
  - repo: local
    hooks:
      - id: go-mod-tidy
        name: go mod tidy
        entry: sh
        args: ["-c", "cd user_service && go mod tidy"]
        language: system
        files: ^user_service/.*\.go$
        pass_filenames: false

  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: sh
        args: ["-c", "cd user_service && golangci-lint run ./..."]
        language: system
        files: ^user_service/.*\.go$
        pass_filenames: false

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
        files: ^user_service/.*\.go$

  - repo: local
    hooks:
      - id: golines
        name: golines
        entry: golines
        args: ["-w", "--max-len=120", "."]
        language: system
        types: [go]
        always_run: true
        files: ^user_service/.*\.go$
        pass_filenames: false

  - repo: local
    hooks:
      - id: gci
        name: gci
        entry: gci
        args: ["write", "."]
        language: system
        types: [go]
        always_run: true
        files: ^user_service/.*\.go$
        pass_filenames: false

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args:
          - --line-length=100
          - --include='\.pyi?$'
          - --exclude="""\.get |
            \.__pycache__|
            \.mypy_cache|
            \.venv|
            build|
            dist"""
        language_version: python3.11
        files: ^data_service/
