repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args:
          - --line-length=100
          - --include='\.pyi?$'
          - --exclude="""\.get |
            \.__pycache__|
            \.mypy_cache|
            \.venv|
            build|
            dist"""
        language_version: python3.11
