repos:
-   repo: local
    hooks:
    -   id: yapf
        name: yapf
        entry: yapf
        language: system
        types: [python]
        args: [--style, .style.yapf, --recursive, --in-place, .]
