services:
  app:
    build:
      context: .
      target: app
    ports:
      - "80:80"
    entrypoint: ["/code/entrypoint.sh"]
    profiles: ["service", "service-local"]

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=local-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d local-db"]
      interval: 5s
      timeout: 5s
      retries: 5
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"
    profiles: ["service-local", "test"]

  local-init:
    build:
      context: .
      target: local-init
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/local-db
      - POSTGRES_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy
    command: ["/code/local_init.sh"]
    profiles: ["service-local", "test"]

  pipeline:
    build:
      context: .
      target: pipeline
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/local-db
    profiles: ["pipeline"]

  test:
    build:
      context: .
      target: test
    depends_on:
      local-init:
        condition: service_completed_successfully
    profiles: ["test"]

volumes:
  postgres_data: