CATEGORIZATION_KEYWORDS = {
    "government_operation": {
        "appropriations": [
            "appropriation",
            "funding",
            "allocation",
            "budget authorization",
            "spending bill",
            "fiscal year",
        ],
        "federal_agencies": [
            "agency",
            "department",
            "bureau",
            "commission",
            "federal entity",
            "government body",
        ],
        "government_oversight": [
            "oversight",
            "accountability",
            "inspector general",
            "government audit",
            "investigation",
        ],
        "government_reform": [
            "reform",
            "reorganization",
            "modernization",
            "efficiency",
            "government improvement",
        ],
        "federal_employment": [
            "federal employee",
            "civil service",
            "personnel",
            "government workforce",
            "public servant",
        ],
        "public_administration": [
            "administrative",
            "bureaucracy",
            "procedure",
            "regulatory process",
            "public management",
        ],
        "government_transparency": [
            "transparency",
            "disclosure",
            "open government",
            "freedom of information",
            "public record",
        ],
    },
    "healthcare": {
        "public_health": [
            "public health",
            "disease",
            "epidemic",
            "pandemic",
            "prevention",
            "vaccination",
        ],
        "insurance": [
            "insurance",
            "coverage",
            "premium",
            "medicaid",
            "medicare",
            "affordable care",
        ],
        "mental_health": [
            "mental health",
            "psychology",
            "psychiatry",
            "counseling",
            "therapy",
        ],
        "pharmaceuticals": [
            "drug",
            "pharmaceutical",
            "medication",
            "prescription",
            "pharmacy",
        ],
        "medical_research": [
            "research",
            "clinical trial",
            "biotechnology",
            "innovation",
            "development",
        ],
        "healthcare_workforce": [
            "doctor",
            "nurse",
            "physician",
            "provider",
            "practitioner",
            "workforce",
            "hospital",
        ],
        "patient_rights": [
            "patient rights",
            "privacy",
            "consent",
            "autonomy",
            "protection",
            "telehealth",
        ],
    },
    "education": {
        "k12": [
            "elementary",
            "middle school",
            "high school",
            "k-12",
            "primary education",
            "secondary education",
        ],
        "higher_education": [
            "university",
            "college",
            "higher education",
            "campus",
            "degree",
            "undergraduate",
            "graduate",
        ],
        "vocational": [
            "vocational",
            "technical",
            "trade school",
            "apprenticeship",
            "certification",
            "skill development",
        ],
        "special_education": [
            "special education",
            "disability",
            "inclusive",
            "accommodation",
            "individualized education",
        ],
        "educational_technology": [
            "educational technology",
            "digital learning",
            "online education",
            "e-learning",
        ],
        "teacher_development": [
            "teacher",
            "faculty",
            "professor",
            "educator",
            "professional development",
        ],
        "student_support": [
            "student loan",
            "financial aid",
            "scholarship",
            "grant",
            "student assistance",
        ],
    },
    "infrastructure": {
        "transportation": [
            "highway",
            "road",
            "bridge",
            "transit",
            "railway",
            "airport",
            "port",
            "transportation",
        ],
        "energy": ["energy", "power", "grid", "electricity", "utility", "transmission"],
        "water": [
            "water",
            "sewage",
            "sanitation",
            "clean water",
            "wastewater",
            "drinking water",
        ],
        "telecommunications": [
            "broadband",
            "internet",
            "telecommunication",
            "connectivity",
            "network",
            "digital infrastructure",
        ],
        "urban_development": [
            "urban",
            "city",
            "municipal",
            "community development",
            "housing",
            "public space",
        ],
        "rural_development": [
            "rural",
            "agricultural infrastructure",
            "rural development",
            "community facilities",
        ],
        "public_facilities": [
            "public building",
            "facility",
            "government property",
            "public works",
        ],
    },
    "economy": {
        "taxation": ["tax", "revenue", "exemption", "deduction", "credit", "taxpayer"],
        "trade": ["trade", "export", "import", "tariff", "commerce", "international trade"],
        "labor": [
            "labor",
            "employment",
            "worker",
            "wage",
            "compensation",
            "collective bargaining",
            "workforce",
        ],
        "small_business": [
            "small business",
            "entrepreneur",
            "startup",
            "business owner",
            "enterprise",
        ],
        "financial_regulation": [
            "regulation",
            "banking",
            "securities",
            "investor protection",
            "market oversight",
        ],
        "monetary_policy": [
            "federal reserve",
            "interest rate",
            "monetary",
            "inflation",
            "currency",
        ],
        "economic_development": [
            "economic growth",
            "development",
            "investment",
            "revitalization",
            "opportunity zone",
        ],
    },
    "defense": {
        "armed_forces": [
            "military",
            "army",
            "navy",
            "air force",
            "marine",
            "armed forces",
            "defense department",
        ],
        "veterans": [
            "veteran",
            "service member",
            "military personnel",
            "veteran affairs",
            "benefits",
        ],
        "national_security": [
            "national security",
            "homeland security",
            "intelligence",
            "counterterrorism",
        ],
        "cybersecurity": [
            "cybersecurity",
            "cyber defense",
            "cyber warfare",
            "information security",
        ],
        "defense_procurement": [
            "procurement",
            "acquisition",
            "contractor",
            "defense industry",
            "weapons system",
        ],
        "military_operations": [
            "deployment",
            "operation",
            "combat",
            "mission",
            "readiness",
            "training",
        ],
        "international_alliances": [
            "nato",
            "alliance",
            "treaty",
            "cooperation",
            "mutual defense",
        ],
    },
    "justice": {
        "criminal_justice": [
            "criminal",
            "prosecution",
            "offender",
            "sentencing",
            "prison",
            "jail",
            "incarceration",
        ],
        "civil_rights": [
            "civil rights",
            "discrimination",
            "equality",
            "minority",
            "protected class",
        ],
        "judicial_system": [
            "court",
            "judge",
            "judiciary",
            "judicial system",
            "supreme court",
            "appellate",
        ],
        "law_enforcement": [
            "police",
            "law enforcement",
            "officer",
            "federal bureau",
            "investigation",
        ],
        "immigration": [
            "immigration",
            "immigrant",
            "asylum",
            "refugee",
            "border",
            "citizenship",
        ],
        "juvenile_justice": [
            "juvenile",
            "youth",
            "minor",
            "juvenile detention",
            "rehabilitation",
        ],
        "legal_services": [
            "legal aid",
            "public defender",
            "legal assistance",
            "access to justice",
        ],
    },
    "environment": {
        "climate_change": [
            "climate change",
            "global warming",
            "greenhouse gas",
            "carbon emission",
            "paris agreement",
        ],
        "conservation": [
            "conservation",
            "protected land",
            "wildlife",
            "habitat",
            "biodiversity",
            "preservation",
        ],
        "pollution": [
            "pollution",
            "contaminant",
            "clean air",
            "clean water",
            "waste management",
            "toxic",
        ],
        "renewable_energy": [
            "renewable",
            "solar",
            "wind",
            "geothermal",
            "alternative energy",
            "clean energy",
        ],
        "natural_resources": [
            "natural resource",
            "mineral",
            "forest",
            "land management",
            "public land",
            "extraction",
        ],
        "environmental_regulation": [
            "environmental protection",
            "regulation",
            "standard",
            "compliance",
            "permit",
        ],
        "sustainability": [
            "sustainable",
            "sustainability",
            "green",
            "eco-friendly",
            "environmental stewardship",
        ],
    },
    "technology": {
        "digital_privacy": [
            "data privacy",
            "personal information",
            "data protection",
            "privacy rights",
        ],
        "artificial_intelligence": [
            "artificial intelligence",
            "ai",
            "machine learning",
            "neural network",
            "algorithm",
        ],
        "biotechnology": [
            "biotechnology",
            "genetic",
            "biological research",
            "biological innovation",
        ],
        "space": ["space", "nasa", "satellite", "aerospace", "orbital", "launch"],
        "research_funding": [
            "research funding",
            "science funding",
            "grant",
            "laboratory",
            "innovation funding",
        ],
        "tech_regulation": [
            "technology regulation",
            "platform regulation",
            "antitrust",
            "tech policy",
        ],
        "digital_governance": [
            "digital governance",
            "internet policy",
            "digital rights",
            "cyber law",
        ],
    },
    "agriculture": {
        "farming": ["farm", "agricultural", "crop", "livestock", "ranch", "farmer"],
        "food_safety": [
            "food safety",
            "inspection",
            "contamination",
            "foodborne illness",
            "processing",
        ],
        "rural_communities": ["rural community", "rural economy", "agricultural community"],
        "agricultural_trade": [
            "agricultural export",
            "agricultural import",
            "farm trade",
            "commodity",
        ],
        "conservation": [
            "conservation",
            "sustainable agriculture",
            "soil",
            "water conservation",
        ],
        "food_assistance": [
            "food assistance",
            "nutrition program",
            "food insecurity",
            "hunger",
        ],
        "agricultural_research": [
            "agricultural research",
            "crop science",
            "animal science",
            "agricultural technology",
        ],
    },
    "social_welfare": {
        "poverty_reduction": [
            "poverty",
            "low-income",
            "disadvantaged",
            "economic security",
            "safety net",
        ],
        "housing": [
            "housing",
            "homelessness",
            "affordable housing",
            "shelter",
            "public housing",
            "rental",
        ],
        "child_welfare": [
            "child welfare",
            "foster care",
            "adoption",
            "child protection",
            "abuse",
            "neglect",
        ],
        "elder_care": [
            "elderly",
            "senior",
            "aging",
            "nursing home",
            "long-term care",
            "retirement",
        ],
        "disability_services": [
            "disability",
            "disabled",
            "accessibility",
            "accommodation",
            "support services",
        ],
        "income_security": [
            "social security",
            "supplemental income",
            "income support",
            "welfare",
            "benefits",
        ],
        "community_development": [
            "community development",
            "neighborhood",
            "local initiative",
            "revitalization",
        ],
    },
    "foreign_policy": {
        "diplomacy": [
            "diplomatic",
            "embassy",
            "international relations",
            "foreign service",
            "state department",
        ],
        "international_aid": [
            "foreign aid",
            "development assistance",
            "humanitarian aid",
            "relief",
        ],
        "sanctions": [
            "sanction",
            "embargo",
            "restriction",
            "economic pressure",
            "foreign policy tool",
        ],
        "treaties": [
            "treaty",
            "agreement",
            "convention",
            "protocol",
            "international law",
            "ratification",
        ],
        "international_organizations": [
            "united nations",
            "world health",
            "international monetary",
            "world bank",
        ],
        "human_rights": [
            "human rights",
            "democracy promotion",
            "freedom",
            "political freedom",
            "oppression",
        ],
        "conflict_resolution": [
            "peace process",
            "mediation",
            "conflict resolution",
            "peacekeeping",
            "stabilization",
        ],
    },
}
