// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package referendumapp

// schema: com.referendumapp.bill.version

import (
	comatproto "github.com/bluesky-social/indigo/api/atproto"
	// "github.com/bluesky-social/indigo/lex/util"
	"github.com/referendumApp/referendumServices/internal/repo"
)

func init() {
	// util.RegisterType("com.referendumapp.bill.version", &BillVersion{})
	// util.RegisterType("com.referendumapp.bill.version#versionRef", &BillVersion_VersionRef{})
}

// RECORDTYPE: BillVersion
type BillVersion struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=com.referendumapp.bill.version" validate:"required"`
	Date          string `json:"date" cborgen:"date" validate:"required,datetime"`
	// url: The url containing the full bill text.
	Url         string                  `json:"url" cborgen:"url" validate:"required"`
	Version     *BillVersion_VersionRef `json:"version" cborgen:"version" validate:"required"`
	VersionType string                  `json:"versionType" cborgen:"versionType" validate:"required,oneof=Introduced,oneof=Comm Sub,oneof=Amended,oneof=Engrossed,oneof=Enrolled,oneof=Chaptered,oneof=Fiscal Note,oneof=Analysis,oneof=Draft,oneof=Conference Sub,oneof=Prefiled,oneof=Veto Message,oneof=Veto Response,oneof=Substitute"`
}

// BillVersion_VersionRef is a "versionRef" in the com.referendumapp.bill.version schema.
//
// RECORDTYPE: BillVersion_VersionRef
type BillVersion_VersionRef struct {
	LexiconTypeID string                    `json:"$type" cborgen:"$type,const=com.referendumapp.bill.version#versionRef" validate:"required"`
	Bill          *comatproto.RepoStrongRef `json:"bill" cborgen:"bill" validate:"required"`
	Previous      *comatproto.RepoStrongRef `json:"previous" cborgen:"previous" validate:"required"`
}

func (t BillVersion) NSID() string {
	return "com.referendumapp.bill.version"
}

func (t BillVersion) Key() string {
	return repo.NextTID()
}
