// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package referendumapp

// schema: com.referendumapp.bill.action

import (
	comatproto "github.com/bluesky-social/indigo/api/atproto"
	"github.com/bluesky-social/indigo/lex/util"
	"github.com/referendumApp/referendumServices/internal/repo"
)

func init() {
	util.RegisterType("com.referendumapp.bill.action", &BillAction{})
}

// RECORDTYPE: BillAction
type BillAction struct {
	LexiconTypeID   string                    `json:"$type" cborgen:"$type,const=com.referendumapp.bill.action" validate:"required"`
	Bill            *comatproto.RepoStrongRef `json:"bill,omitempty" cborgen:"bill,omitempty" validate:"omitempty"`
	Date            string                    `json:"date" cborgen:"date" validate:"required,datetime"`
	Description     string                    `json:"description" cborgen:"description" validate:"required"`
	LegislativeBody string                    `json:"legislativeBody" cborgen:"legislativeBody" validate:"required"`
}

func (t BillAction) NSID() string {
	return "com.referendumapp.bill.action"
}

func (t BillAction) Key() string {
	return repo.NextTID()
}
