// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package referendumapp

// schema: com.referendumapp.legislator.vote

import (
	comatproto "github.com/bluesky-social/indigo/api/atproto"
	// "github.com/bluesky-social/indigo/lex/util"
	"github.com/referendumApp/referendumServices/internal/repo"
)

func init() {
	// util.RegisterType("com.referendumapp.legislator.vote", &LegislatorVote{})
}

// RECORDTYPE: LegislatorVote
type LegislatorVote struct {
	LexiconTypeID string                    `json:"$type" cborgen:"$type,const=com.referendumapp.legislator.vote" validate:"required"`
	BillAction    *comatproto.RepoStrongRef `json:"billAction" cborgen:"billAction" validate:"required"`
	Choice        *string                   `json:"choice,omitempty" cborgen:"choice,omitempty" validate:"omitempty,oneof=Yay,oneof=Nay,oneof=Absent,oneof=Abstain"`
}

func (t LegislatorVote) NSID() string {
	return "com.referendumapp.legislator.vote"
}

func (t LegislatorVote) Key() string {
	return repo.NextTID()
}
