// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package referendumapp

// schema: com.referendumapp.legislator.sponsor

import (
	comatproto "github.com/bluesky-social/indigo/api/atproto"
	// "github.com/bluesky-social/indigo/lex/util"
	"github.com/referendumApp/referendumServices/internal/repo"
)

func init() {
	// util.RegisterType("com.referendumapp.legislator.sponsor", &LegislatorSponsor{})
}

// RECORDTYPE: LegislatorSponsor
type LegislatorSponsor struct {
	LexiconTypeID string                    `json:"$type" cborgen:"$type,const=com.referendumapp.legislator.sponsor" validate:"required"`
	Bill          *comatproto.RepoStrongRef `json:"bill" cborgen:"bill" validate:"required"`
	Rank          int64                     `json:"rank" cborgen:"rank" validate:"required"`
	Type          string                    `json:"type" cborgen:"type" validate:"required,oneof=Primary Sponsor,oneof=Co-Sponsor"`
}

func (t LegislatorSponsor) NSID() string {
	return "com.referendumapp.legislator.sponsor"
}

func (t LegislatorSponsor) Key() string {
	return repo.NextTID()
}
