// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package referendumapp

// schema: com.referendumapp.person.legislatorFollow

import (
	"github.com/bluesky-social/indigo/lex/util"
	"github.com/bluesky-social/indigo/repo"
)

func init() {
	util.RegisterType("com.referendumapp.person.legislatorFollow", &PersonLegislatorFollow{})
}

// RECORDTYPE: PersonLegislatorFollow
type PersonLegislatorFollow struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=com.referendumapp.person.legislatorFollow" validate:"required"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt" validate:"required,datetime"`
	Legislator    string `json:"legislator" cborgen:"legislator" validate:"required,did"`
}

// PersonLegislatorFollow_Input is the input argument to a com.referendumapp.person.legislatorFollow call.
type PersonLegislatorFollow_Input struct {
	// did: Atproto DID to follow.
	Did string `json:"did" cborgen:"did" validate:"required,did"`
}

func (t PersonLegislatorFollow) NSID() string {
	return "com.referendumapp.person.legislatorFollow"
}

func (t PersonLegislatorFollow) Key() string {
	return repo.NextTID()
}
