// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package referendumapp

// schema: com.referendumapp.server.createBill

import (
	"github.com/referendumApp/referendumServices/internal/domain/atp"
)

// ServerCreateBill_Input is the input argument to a com.referendumapp.server.createBill call.
type ServerCreateBill_Input struct {
	BillId          int64  `json:"billId" cborgen:"billId" validate:"required"`
	Identifier      string `json:"identifier" cborgen:"identifier" validate:"required"`
	LegislativeBody string `json:"legislativeBody" cborgen:"legislativeBody" validate:"required"`
	Legislature     string `json:"legislature" cborgen:"legislature" validate:"required"`
	Session         string `json:"session" cborgen:"session" validate:"required"`
	Status          string `json:"status" cborgen:"status" validate:"required"`
	StatusDate      string `json:"statusDate" cborgen:"statusDate" validate:"required"`
	Title           string `json:"title" cborgen:"title" validate:"required"`
}

// ServerCreateBill_Output is the output of a com.referendumapp.server.createBill call.
//
// Confirmation returned on successful bill creation.
type ServerCreateBill_Output struct {
	Aid *atp.Aid `json:"aid,omitempty" cborgen:"aid,omitempty" validate:"omitempty"`
	Cid string   `json:"cid" cborgen:"cid" validate:"required"`
}
