// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package referendumapp

// schema: com.referendumapp.server.createSystemUser

// ServerCreateSystemUser_Input is the input argument to a com.referendumapp.server.createSystemUser call.
type ServerCreateSystemUser_Input struct {
	DisplayName *string `json:"displayName,omitempty" cborgen:"displayName,omitempty" validate:"omitempty,max=60"`
	Email       string  `json:"email" cborgen:"email" validate:"required,email,max=60"`
	// handle: Requested handle for the account.
	Handle string `json:"handle" cborgen:"handle" validate:"required,handle"`
}

// ServerCreateSystemUser_Output is the output of a com.referendumapp.server.createSystemUser call.
//
// Account login session returned on successful account creation.
type ServerCreateSystemUser_Output struct {
	ApiKey string `json:"apiKey" cborgen:"apiKey" validate:"required"`
	// did: The DID of the new account.
	Did    string `json:"did" cborgen:"did" validate:"required,did"`
	Handle string `json:"handle" cborgen:"handle" validate:"required,handle"`
}
