// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package referendumapp

// schema: com.referendumapp.server.createLegislator

import (
	"github.com/bluesky-social/indigo/lex/util"
)

// ServerCreateLegislator_Input is the input argument to a com.referendumapp.server.createLegislator call.
type ServerCreateLegislator_Input struct {
	Address           *string       `json:"address,omitempty" cborgen:"address,omitempty" validate:"omitempty"`
	District          string        `json:"district" cborgen:"district" validate:"required"`
	Facebook          *string       `json:"facebook,omitempty" cborgen:"facebook,omitempty" validate:"omitempty"`
	FollowthemoneyEid *string       `json:"followthemoneyEid,omitempty" cborgen:"followthemoneyEid,omitempty" validate:"omitempty"`
	Image             *util.LexBlob `json:"image,omitempty" cborgen:"image,omitempty" validate:"omitempty"`
	ImageUrl          *string       `json:"imageUrl,omitempty" cborgen:"imageUrl,omitempty" validate:"omitempty"`
	Instagram         *string       `json:"instagram,omitempty" cborgen:"instagram,omitempty" validate:"omitempty"`
	LegislatorId      int64         `json:"legislatorId" cborgen:"legislatorId" validate:"required"`
	Legislature       string        `json:"legislature" cborgen:"legislature" validate:"required"`
	Name              string        `json:"name" cborgen:"name" validate:"required"`
	Party             string        `json:"party" cborgen:"party" validate:"required"`
	Phone             *string       `json:"phone,omitempty" cborgen:"phone,omitempty" validate:"omitempty,e164"`
	Role              string        `json:"role" cborgen:"role" validate:"required"`
	State             string        `json:"state" cborgen:"state" validate:"required"`
	Twitter           *string       `json:"twitter,omitempty" cborgen:"twitter,omitempty" validate:"omitempty"`
}

// ServerCreateLegislator_Output is the output of a com.referendumapp.server.createLegislator call.
//
// Confirmation returned on successful legislator creation.
type ServerCreateLegislator_Output struct {
	Did    string `json:"did" cborgen:"did" validate:"required,did"`
	Handle string `json:"handle" cborgen:"handle" validate:"required,handle"`
}
