// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package referendumapp

// schema: com.referendumapp.server.createLegislator

// ServerCreateLegislator_Input is the input argument to a com.referendumapp.server.createLegislator call.
type ServerCreateLegislator_Input struct {
	// address: Official address of the legislator.
	Address *string `json:"address,omitempty" cborgen:"address,omitempty" validate:"omitempty,max=255"`
	// district: District number or identifier.
	District string `json:"district" cborgen:"district" validate:"required,max=20"`
	// followthemoneyEid: FollowTheMoney entity ID.
	FollowthemoneyEid *string `json:"followthemoneyEid,omitempty" cborgen:"followthemoneyEid,omitempty" validate:"omitempty,max=50"`
	// imageUrl: URL to the legislator's photo.
	ImageUrl *string `json:"imageUrl,omitempty" cborgen:"imageUrl,omitempty" validate:"omitempty,uri"`
	// legiscanId: Unique legislator identifier from Legiscan.
	LegiscanId *int64 `json:"legiscanId,omitempty" cborgen:"legiscanId,omitempty" validate:"omitempty"`
	// level: Jurisdiction of the legislator's legislature: Federal, State, or Local.
	Level *string `json:"level,omitempty" cborgen:"level,omitempty" validate:"omitempty"`
	// name: Full name of the legislator.
	Name string `json:"name" cborgen:"name" validate:"required,max=100"`
	// party: Legislator's party.
	Party *string `json:"party,omitempty" cborgen:"party,omitempty" validate:"omitempty"`
	// phone: Contact phone number.
	Phone *string `json:"phone,omitempty" cborgen:"phone,omitempty" validate:"omitempty,max=20"`
	// representingState: For federal legislators, the state that they represent
	RepresentingState *string `json:"representingState,omitempty" cborgen:"representingState,omitempty" validate:"omitempty"`
	// role: Legislator role, ie Representative or Senator.
	Role *string `json:"role,omitempty" cborgen:"role,omitempty" validate:"omitempty"`
}

// ServerCreateLegislator_Output is the output of a com.referendumapp.server.createLegislator call.
//
// Created legislator record information.
type ServerCreateLegislator_Output struct {
	// address: Official address of the legislator.
	Address *string `json:"address,omitempty" cborgen:"address,omitempty" validate:"omitempty"`
	// district: District number or identifier.
	District string `json:"district" cborgen:"district" validate:"required"`
	// followthemoneyEid: FollowTheMoney entity ID.
	FollowthemoneyEid *string `json:"followthemoneyEid,omitempty" cborgen:"followthemoneyEid,omitempty" validate:"omitempty"`
	// id: Internal system identifier for the created legislator record.
	Id int64 `json:"id" cborgen:"id" validate:"required"`
	// imageUrl: URL to the legislator's photo.
	ImageUrl *string `json:"imageUrl,omitempty" cborgen:"imageUrl,omitempty" validate:"omitempty"`
	// legiscanId: Unique legislator identifier from Legiscan.
	LegiscanId *int64 `json:"legiscanId,omitempty" cborgen:"legiscanId,omitempty" validate:"omitempty"`
	// name: Full name of the legislator.
	Name string `json:"name" cborgen:"name" validate:"required"`
	// party: Legislator's party
	Party *string `json:"party,omitempty" cborgen:"party,omitempty" validate:"omitempty"`
	// phone: Contact phone number.
	Phone *string `json:"phone,omitempty" cborgen:"phone,omitempty" validate:"omitempty"`
	// representingState: For federal legislators, the state that they represent
	RepresentingState *string `json:"representingState,omitempty" cborgen:"representingState,omitempty" validate:"omitempty"`
	// role: Legislator role, ie Representative or Senator
	Role *string `json:"role,omitempty" cborgen:"role,omitempty" validate:"omitempty"`
	// state: Jurisdiction of the legislator's legislature
	State *string `json:"state,omitempty" cborgen:"state,omitempty" validate:"omitempty"`
}
