// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package referendumapp

// schema: com.referendumapp.user.legislatorFollow

import (
	"github.com/bluesky-social/indigo/lex/util"
	"github.com/referendumApp/referendumServices/internal/repo"
)

func init() {
	util.RegisterType("com.referendumapp.user.legislatorFollow", &UserLegislatorFollow{})
}

// RECORDTYPE: UserLegislatorFollow
type UserLegislatorFollow struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=com.referendumapp.user.legislatorFollow" validate:"required"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt" validate:"required,datetime"`
	Legislator    string `json:"legislator" cborgen:"legislator" validate:"required,did"`
}

// UserLegislatorFollow_Input is the input argument to a com.referendumapp.user.legislatorFollow call.
type UserLegislatorFollow_Input struct {
	// did: Atproto DID to follow.
	Did string `json:"did" cborgen:"did" validate:"required,did"`
}

func (t UserLegislatorFollow) NSID() string {
	return "com.referendumapp.user.legislatorFollow"
}

func (t UserLegislatorFollow) Key() string {
	return repo.NextTID()
}
