// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package referendumapp

// schema: com.referendumapp.user.billFollow

import (
	comatproto "github.com/bluesky-social/indigo/api/atproto"
	"github.com/bluesky-social/indigo/lex/util"
	"github.com/referendumApp/referendumServices/internal/repo"
)

func init() {
	util.RegisterType("com.referendumapp.user.billFollow", &UserBillFollow{})
}

// RECORDTYPE: UserBillFollow
type UserBillFollow struct {
	LexiconTypeID string                    `json:"$type" cborgen:"$type,const=com.referendumapp.user.billFollow" validate:"required"`
	Bill          *comatproto.RepoStrongRef `json:"bill" cborgen:"bill" validate:"required"`
	CreatedAt     string                    `json:"createdAt" cborgen:"createdAt" validate:"required,datetime"`
}

// UserBillFollow_Input is the input argument to a com.referendumapp.user.billFollow call.
type UserBillFollow_Input struct {
	// bid: Referendum bill ID (BID) to follow.
	Bid string `json:"bid" cborgen:"bid" validate:"required,bid"`
}

func (t UserBillFollow) NSID() string {
	return "com.referendumapp.user.billFollow"
}

func (t UserBillFollow) Key() string {
	return repo.NextTID()
}
