// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package referendumapp

// schema: com.referendumapp.user.profile

import (
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	// util.RegisterType("com.referendumapp.user.profile", &UserProfile{})
}

// RECORDTYPE: UserProfile
type UserProfile struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=com.referendumapp.user.profile" validate:"required"`
	// avatar: Small image to be displayed next to posts from account. AKA, 'profile picture'
	Avatar    *util.LexBlob `json:"avatar,omitempty" cborgen:"avatar,omitempty" validate:"omitempty"`
	CreatedAt *string       `json:"createdAt,omitempty" cborgen:"createdAt,omitempty" validate:"omitempty,datetime"`
	// description: Free-form profile description text.
	Description *string `json:"description,omitempty" cborgen:"description,omitempty" validate:"omitempty,max=2560"`
	DisplayName *string `json:"displayName,omitempty" cborgen:"displayName,omitempty" validate:"omitempty,name,max=60"`
}

func (t UserProfile) NSID() string {
	return "com.referendumapp.user.profile"
}

func (t UserProfile) Key() string {
	return "self"
}
