[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "referendumServices"
dynamic = ["version"]
description = ""
authors = [{name = "Makani Dalton", email = "makani@referendumapp.com"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic==1.15.2",
    "argon2-cffi==23.1.0",
    "boto3==1.37.32",
    "debugpy==1.8.14",
    "fastapi[standard]",
    "google-api-python-client==2.166.0",
    "google-auth==2.38.0",
<<<<<<< HEAD
    "google-auth-httplib2==0.2.0",
    "google-auth-oauthlib",
    "langchain==0.3.19",
    "langchain-community==0.3.17",
    "langchain-openai==0.3.6",
    "openai==1.63.2",
=======
    "langchain==0.3.23",
    "langchain-community==0.3.21",
    "langchain-openai==0.3.12",
    "openai==1.72.0",
>>>>>>> main
    "pandas==2.2.3",
    "passlib==1.7.4",
    "pdfminer.six==20250327",
    "psycopg2-binary==2.9.10",
    "pydantic==2.11.3",
    "pydantic-settings==2.8.1",
    "python-jose==3.4.0",
    "requests==2.32.3",
    "sqlalchemy==2.0.40",
    "tenacity==9.1.2",
    "watchtower==3.4.0"
]

[project.optional-dependencies]
test = ["black", "httpx", "pytest", "pytest-asyncio"]

[tool.black]
line-length = 100
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
    /(
      # directories
      \.eggs
      | \.git
      | \.hg
      | \.mypy_cache
      | \.tox
      | \.venv
      | build
      | dist
    )/
    '''

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"
