name: Run ATP Service Tests

on:
  push:
    branches: [ main ]
    paths:
      - "atp_service/**"
      - ".github/workflows/atp_service_test.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "atp_service/**"
      - ".github/workflows/atp_service_test.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v5
      with:
          go-version: "1.24"
          cache: true
          cache-dependency-path: atp_service/go.sum

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        working-directory: atp_service
        args: --out-format=colored-line-number
