name: Deploy API to AWS

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (prod/dev)'
        required: true
        default: 'dev'

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: referendum/api
  EC2_INSTANCE_ID: i-08edd9a77b42449b2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set deployment variables
      run: |
        if [[ "${{ github.event_name }}" == "push" ]]; then
          DEPLOY_ENV="prod"
        else
          DEPLOY_ENV="${{ github.event.inputs.environment }}"
        fi
        echo "DEPLOY_ENV=$DEPLOY_ENV" >> $GITHUB_ENV
        echo "IMAGE_TAG=$DEPLOY_ENV-${{ github.sha }}" >> $GITHUB_ENV
        echo "PORT_MAPPING=$([ "$DEPLOY_ENV" == "prod" ] && echo "80:80" || echo "8080:80")" >> $GITHUB_ENV

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        set -e
        docker compose --profile api build
        docker tag referendumservices-api:latest $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.IMAGE_TAG }}
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.IMAGE_TAG }}

    - name: Deploy to EC2
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        set -e
        echo "Deploying to EC2..."
        DEPLOY_COMMAND_ID=$(aws ssm send-command \
          --instance-ids "${{ env.EC2_INSTANCE_ID }}" \
          --document-name "AWS-RunShellScript" \
          --parameters '{
            "commands": [
              "set -e",
              "aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}",
              "docker pull ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}",
              "docker stop ${{ env.DEPLOY_ENV }}-app || true",
              "docker rm ${{ env.DEPLOY_ENV }}-app || true",
              "ENV_VARS=$(aws ssm get-parameters-by-path --path /${{ env.DEPLOY_ENV }}/ --with-decryption --query \"Parameters[*].{Name:Name,Value:Value}\" --output json | jq -r \".[].Name + \\\"=\\\" + .[].Value\" | tr \"\\n\" \" \" | sed \"s/\\/[^\\/]*\\///g\" | sed \"s/^/export /\" | tr \"\\n\" \" \")",
              "docker run -d --name ${{ env.DEPLOY_ENV }}-app -p ${{ env.PORT_MAPPING }} --env-file <(echo \"$ENV_VARS\") ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}",
              "docker system prune -f",
              "echo ${{ env.DEPLOY_ENV }} deployment completed"
            ]
          }' \
          --output text \
          --query "Command.CommandId")
        
        # Wait for the command to complete and check its status
        while true; do
          STATUS=$(aws ssm list-commands \
            --command-id "$DEPLOY_COMMAND_ID" \
            --query "Commands[0].Status" \
            --output text)
          if [ "$STATUS" = "Success" ]; then
            echo "Deployment command executed successfully"
            break
          elif [ "$STATUS" = "Failed" ]; then
            echo "Deployment command failed"
            exit 1
          fi
          echo "Waiting for deployment command to complete..."
          sleep 10
        done

    - name: Verify Deployment
      run: |
        set -e
        echo "Verifying deployment..."
        PORT="${{ env.DEPLOY_ENV == 'prod' && '80' || '8080' }}"
        MAX_RETRIES=5
        RETRY_INTERVAL=10
        
        for i in $(seq 1 $MAX_RETRIES); do
          echo "Attempt $i of $MAX_RETRIES"
          HEALTH_CHECK_COMMAND_ID=$(aws ssm send-command \
            --instance-ids "${{ env.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --parameters "{\"commands\":[\"curl -s -o /dev/null -w \\\"%{http_code}\\\" http://localhost:$PORT/health\"]}" \
            --output text \
            --query "Command.CommandId")
          
          sleep $RETRY_INTERVAL
          
          HEALTH_CHECK_STATUS_CODE=$(aws ssm list-command-invocations \
            --command-id "$HEALTH_CHECK_COMMAND_ID" \
            --details \
            --output text \
            --query "CommandInvocations[].CommandPlugins[].Output")
          
          if [ "$HEALTH_CHECK_STATUS_CODE" == "200" ]; then
            echo "Deployment verified successfully"
            echo "Updating stable tag..."
            docker tag ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.DEPLOY_ENV }}-stable
            docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.DEPLOY_ENV }}-stable
            echo "Deployment successful"
            exit 0
          fi
          
          echo "Health check failed. Status code: $HEALTH_CHECK_STATUS_CODE"
        done
        
        echo "Deployment verification failed after $MAX_RETRIES attempts"
        echo "Rolling back to previous stable version..."
        aws ssm send-command \
          --instance-ids "${{ env.EC2_INSTANCE_ID }}" \
          --document-name "AWS-RunShellScript" \
          --parameters '{
            "commands": [
              "docker stop ${{ env.DEPLOY_ENV }}-app || true",
              "docker rm ${{ env.DEPLOY_ENV }}-app || true",
              "docker rmi ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} || true",
              "ENV_VARS=$(aws ssm get-parameters-by-path --path /${{ env.DEPLOY_ENV }}/ --with-decryption --query \"Parameters[*].{Name:Name,Value:Value}\" --output json | jq -r \".[].Name + \\\"=\\\" + .[].Value\" | tr \"\\n\" \" \" | sed \"s/\\/[^\\/]*\\///g\" | sed \"s/^/export /\" | tr \"\\n\" \" \")",
              "docker run -d --name ${{ env.DEPLOY_ENV }}-app -p ${{ env.PORT_MAPPING }} --env-file <(echo \"$ENV_VARS\") ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.DEPLOY_ENV }}-stable"
            ]
          }'
        exit 1
