name: Run Pipeline Task

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run pipeline for'
        required: true
        default: 'dev'

env:
  AWS_REGION: us-east-2
  PIPELINE_CLUSTER: ETLCluster
  PIPELINE_TASK_DEFINITION: load-referendum-from-legiscan

permissions:
  id-token: write
  contents: read

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Run task
        run: |
          aws ecs run-task \
            --cluster ${{ env.PIPELINE_CLUSTER }} \
            --task-definition ${{ env.PIPELINE_TASK_DEFINITION }} \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={
              subnets=[subnet-030216eccd9d8d317],
              securityGroups=[sg-0ddba9c80c77125c2,sg-0d65a5b9089171007],
              assignPublicIp=DISABLED
            }" \
            --tags key=Environment,value=${{ github.event.inputs.environment }}
