name: Run Pipeline Task

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run pipeline for'
        required: true
        default: 'dev'
        type: 'choice'
        options:
          - dev
          - prod

env:
  AWS_REGION: us-east-2
  PIPELINE_CLUSTER: ETLCluster
  PIPELINE_TASK_DEFINITION: load-referendum-from-legiscan

permissions:
  id-token: write
  contents: read

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Run task
        run: |
          aws ecs run-task \
            --cluster ${{ env.PIPELINE_CLUSTER }} \
            --task-definition ${{ env.PIPELINE_TASK_DEFINITION }}-${{ github.event.inputs.environment }} \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={
              subnets=[subnet-0eeb47118647abbb5],
              securityGroups=[sg-0a4b16a640c6f2d13,sg-01d5891e4bb9f564a],
              assignPublicIp=ENABLED
            }" \
            --tags key=Environment,value=${{ github.event.inputs.environment }}
