name: Run Pipeline Task

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (prod/dev)'
        required: true
        default: 'dev'

env:
  AWS_ACCOUNT_ID: 842675976781
  AWS_REGION: us-east-2
  ECR_REPOSITORY_API: referendum/api
  ECR_REPOSITORY_PIPELINE: referendum/pipeline
  POSTGRES_PASSWORD_SECRET_NAME: rds!db-a5c629ff-4d6e-4d68-9680-6cdab848369c
  API_ACCESS_TOKEN_SECRET_NAME: /system/API_ACCESS_TOKEN
  SECRET_KEY_SECRET_NAME: /system/SECRET_KEY
  PIPELINE_CLUSTER: ETLCluster
  PIPELINE_TASK_DEFINITION: load-referendum-from-legiscan

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}
      - name: Run task
        run: |
          aws ecs run-task \
            --cluster ${{ env.PIPELINE_CLUSTER }} \
            --task-definition ${{ env.PIPELINE_TASK_DEFINITION }} \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={
              subnets=[subnet-030216eccd9d8d317],
              securityGroups=[sg-0c0a90439deaf8b68,sg-0d65a5b9089171007],
              assignPublicIp=DISABLED
            }" \
            --tags key=Environment,value=${{ github.event.inputs.environment }}
