name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and run tests
      run: |
        docker compose --profile test build
        docker compose --profile test run --rm test
    - name: Clean up
      if: always()
      run: docker compose --profile test down