name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run API Tests
      run: |
        docker compose --profile test build
        docker compose --profile test run --rm test pytest api/ common/

    - name: Clean up after API tests
      if: always()
      run: docker compose --profile test down

    - name: Run Pipeline Tests
      run: |
        docker compose --profile test build
        docker compose --profile test run --rm test pytest pipeline/

    - name: Final cleanup
      if: always()
      run: docker compose --profile test down
