name: Run User Service Tests

on:
  push:
    branches: [main]
    paths:
      - "user_service/**"
      - ".github/workflows/user_service_test.yml"
  pull_request:
    branches: [main]
    paths:
      - "user_service/**"
      - ".github/workflows/user_service_test.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true
          cache-dependency-path: user_service/go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          working-directory: user_service

  build-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true
          cache-dependency-path: user_service/go.sum

      - name: Build Lexicon Schema
        working-directory: user_service
        run: go run ./cmd/lexgen --build-file ./cmd/lexgen/build-config.json "./cmd/lexgen/lexicons/com/referendumapp"

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker Layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Migrations Image
      uses: docker/build-push-action@v6
      with:
        context: ./data_service
        file: ./data_service/Dockerfile
        push: false
        load: true
        tags: migrations
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: Set Go cache env vars
      run: |
        echo "GOCACHE=$(go env GOCACHE)" >> $GITHUB_ENV
        echo "GOMODCACHE=$(go env GOMODCACHE)" >> $GITHUB_ENV

    - name: Build Test Image
      uses: docker/build-push-action@v6
      with:
        context: ./user_service
        file: ./user_service/Dockerfile
        push: false
        load: true
        tags: user-test:latest
        # TODO: Bug with resolving the docker host so we're hardcoding the docker host IP from the default bridge
        # https://github.com/docker/buildx/issues/1832
        add-hosts: host.docker.internal:172.17.0.1
        build-args: |
          GOMODCACHE=${{ env.GOMODCACHE }}
          GOCACHE=${{ env.GOCACHE }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new2G,mode=max
    
    - name: Run Tests
      run: docker compose run user-test

    - name: Update Cache
      run: |
        rm -rf /tmp/.buildx-cache-old
        mv /tmp/.buildx-cache /tmp/.buildx-cache-old
        mkdir -p /tmp/.buildx-cache
        
        # Merge all cache directories
        for dir in /tmp/.buildx-cache-new*; do
          if [ -d "$dir" ] && [ "$(ls -A "$dir" 2>/dev/null)" ]; then
            cp -r "$dir"/* /tmp/.buildx-cache/ 2>/dev/null || true
            rm -rf "$dir"
          fi
        done
        
        rm -rf /tmp/.buildx-cache-old

    - name: Clean Tests
      if: always()
      run: docker compose down -v
