name: Run User Service Tests

on:
  push:
    branches: [ main ]
    paths:
      - "user_service/**"
      - ".github/workflows/user_service_test.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "user_service/**"
      - ".github/workflows/user_service_test.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v5
      with:
          go-version: "1.24"
          cache: true
          cache-dependency-path: user_service/go.sum

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        working-directory: user_service

          cache: true
          cache-dependency-path: user_service/go.sum
      - name: Build Lexicon Schema
        working-directory: user_service
        run: go run ./cmd/lexgen --build-file ./cmd/lexgen/build-config.json
